# Generated by Django 5.2.10 on 2026-02-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Descripción (Español)'),
        ),
    ]
